export { detectAndRoute, detectInputLanguage, mapOutputLanguageToRoute } from './router'
export { CONFIDENCE_THRESHOLD } from './confidence-scorer'
export { analyzeScripts, getLeadSlice } from './token-analyzer'
export { scoreDialects } from './dialect-patterns'
export { normalizeArabicForMatching } from './arabic-normalize'
